[tool.poetry]
name = "openhands"
version = "0.1.0"
description = ""
authors = ["Akim Tsvigun <aktsvigun@nebius.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
